<#.SYNOPSIS
    Parses Azure Migrate assessment data from an Excel file and extracts virtual machine and disk SKUs.
.DESCRIPTION
    This script retrieves and processes Azure resource data from the output file generated by Azure Migrate, specifically focusing on virtual machine and disk SKUs.
    It outputs the results in the same structured JSON format as Get-AzureServices.ps1, which can then be used for finding appropriate Azure regions where these resources can be deployed.
.PARAMETER filePath
    The path to the Excel file containing the Azure Migrate assessment data.

.PARAMETER outputFile
    The name of the output file where the results will be exported. Default is "resources.json".

.EXAMPLE
    PS C:\> .\Get-RessourcesFromAM.ps1 -filePath "C:\path\to\Assessment.xlsx" -outputFile "C:\path\to\summary.json"
    Runs the script with the specified Excel file and outputs the results to the specified JSON file.

.OUTPUTS
    JSON file containing the queried resource data and extracted properties.

.NOTES
    - Requires Azure PowerShell module to be installed and authenticated.
    - Requires ImportExcel module to be installed for reading Excel files.
    - The script assumes the Excel file has specific worksheets named 'All_Assessed_Machines' and 'All_Assessed_Disks'.

#>

param(
    [Parameter(Mandatory=$true)] [string]$filePath,
    [Parameter(Mandatory = $false)] [string]$outputFile = ".\summary.json" # Json file to export the results to
)

# Start counting individual VM SKUs
# Check if the worksheet 'All_Assessed_Machines' exists in the Excel file
$worksheets = Get-ExcelSheetInfo -Path $filePath
if (-not $worksheets) {
    Write-Output "Error accessing the Excel file: No worksheets found or file could not be read."
    exit
}
$worksheetExists = $worksheets | Where-Object { $_.Name -eq 'All_Assessed_Machines' }
if ( $worksheetExists) {} else {
    Write-Output "Worksheet 'All_Assessed_Machines' not found in the Excel file."
}
# If the worksheet exists, proceed with importing data
# Import the Excel file
$Data = Import-Excel -Path $filePath -WorksheetName 'All_Assessed_Machines' | Group-Object 'Recommended Size' | Sort-Object -Property Count -Descending

# Initialize an empty array for VM SKUs
$VMskus = @()

# Loop through each group and display the recommended VM sizes
foreach ($Group in $Data) {
    Write-Output "Recommended Size: $($Group.Name) - Count: $($Group.Count)"
    # Add to output object
    $VMskus += @{
        vmSize  = $Group.Name
  }
}

# Start counting individual Disk SKUs
# Check if the worksheet 'All_Assessed_Disks' exists in the Excel file
$worksheets = Get-ExcelSheetInfo -Path $filePath
if (-not $worksheets) {
    Write-Output "Error accessing the Excel file: No worksheets found or file could not be read."
    exit
}
$worksheetExists = $worksheets | Where-Object { $_.Name -eq 'All_Assessed_Disks' }
if ( $worksheetExists) {} else {
    Write-Output "Worksheet 'All_Assessed_Disks' not found in the Excel file."
}
# If the worksheet exists, proceed with importing data
# Import the Excel file
$Data = Import-Excel -Path $filePath -WorksheetName 'All_Assessed_Disks' | Group-Object 'Recommended disk size SKU' | Sort-Object -Property Count -Descending

# Initialize an empty array for ResourceSkus
$diskSkus = @()

# Add to output object
foreach ($Group in $Data) {
    Write-Output "Recommended Disk Size SKU: $($Group.Name) - Count: $($Group.Count)"
    $diskSkus += @{
        name = switch -Wildcard ($Group.Name) {
            "PremiumV2*"    { "PremiumV2_LRS"; break }
            "Premium*"      { "Premium_LRS"; break }
            "StandardSSD*"  { "StandardSSD_LRS"; break }
            "Standard*"     { "Standard_LRS"; break }
            "Ultra*"        { "UltraSSD_LRS"; break }
            default         { "Unknown" }
        }
        tier = $Group.Name -replace "Premium|Standard|Ultra", "" # Extract size from SKU name

    }
}

# As long as we don't care about a specific region in the data collection phase, we can use a dummy value
$dummyRegion = "dummyregion"

# Build the final object
$output = @(
    @{
        ResourceCount = $diskSkus.Count
        ResourceType = "microsoft.compute/disks"
        ResourceSkus = $diskSkus
        AzureRegions = @($dummyRegion) # Replace with actual region if needed
    },
    @{
        ResourceCount = $VMskus.Count
        ResourceType = "microsoft.compute/virtualmachines"
        ResourceSkus = $VMskus
        AzureRegions = @($dummyRegion) # Replace with actual region if needed
    }
)

# Convert the output to JSON format
$jsonOutput = $output | ConvertTo-Json -Depth 10
# Save the JSON output to a file
$jsonOutput | Out-File -FilePath $outputFile -Encoding utf8
Write-Output "JSON output saved to $outputFile"
